const resData = [
    {
      id: 1,
      name: "Delicious Bites",
      cuisines: ["Italian", "Mexican"],
      rating: 4.5,
      delivery_time: 30,
      image_url: "https://dummyimage.com/300x200/ffcc00/000000",
    },
    {
      id: 2,
      name: "Tasty Fusion",
      cuisines: ["Asian", "American"],
      rating: 4.2,
      delivery_time: 45,
      image_url: "https://dummyimage.com/300x200/336699/ffffff",
    },
    {
      id: 3,
      name: "Spice Haven",
      cuisines: ["Indian", "Middle Eastern"],
      rating: 4.8,
      delivery_time: 25,
      image_url: "https://dummyimage.com/300x200/993366/ffffff",
    },
    {
      id: 4,
      name: "Sizzling Grill",
      cuisines: ["Steakhouse", "Barbecue"],
      rating: 4.3,
      delivery_time: 40,
      image_url: "https://dummyimage.com/300x200/cc9900/ffffff",
    },
    {
      id: 5,
      name: "Mango Grove",
      cuisines: ["Indian", "Vegetarian"],
      rating: 4.6,
      delivery_time: 35,
      image_url: "https://dummyimage.com/300x200/66cc00/ffffff",
    },
    {
      id: 6,
      name: "Ocean Delight",
      cuisines: ["Seafood", "Sushi"],
      rating: 4.7,
      delivery_time: 50,
      image_url: "https://dummyimage.com/300x200/3366cc/ffffff",
    },
    {
      id: 7,
      name: "Golden Wok",
      cuisines: ["Chinese", "Thai"],
      rating: 4.4,
      delivery_time: 30,
      image_url: "https://dummyimage.com/300x200/996633/ffffff",
    },
    {
      id: 8,
      name: "Pasta Paradise",
      cuisines: ["Italian", "Pasta"],
      rating: 4.2,
      delivery_time: 25,
      image_url: "https://dummyimage.com/300x200/ff6600/ffffff",
    },
    {
      id: 9,
      name: "Burger Haven",
      cuisines: ["American", "Burgers"],
      rating: 4.5,
      delivery_time: 35,
      image_url: "https://dummyimage.com/300x200/9933cc/ffffff",
    },
    {
      id: 10,
      name: "Veggie Delight",
      cuisines: ["Vegetarian", "Healthy"],
      rating: 4.6,
      delivery_time: 40,
      image_url: "https://dummyimage.com/300x200/009900/ffffff",
    },
    {
      id: 11,
      name: "Taco Time",
      cuisines: ["Mexican", "Tacos"],
      rating: 4.3,
      delivery_time: 30,
      image_url: "https://dummyimage.com/300x200/ff0000/ffffff",
    },
    {
      id: 12,
      name: "Crispy Crust",
      cuisines: ["Pizza", "Italian"],
      rating: 4.7,
      delivery_time: 35,
      image_url: "https://dummyimage.com/300x200/663300/ffffff",
    },
    {
      id: 13,
      name: "Noodle House",
      cuisines: ["Asian", "Noodles"],
      rating: 4.4,
      delivery_time: 45,
      image_url: "https://dummyimage.com/300x200/ff99cc/ffffff",
    },
    {
      id: 14,
      name: "Healthy Harvest",
      cuisines: ["Vegetarian", "Organic"],
      rating: 4.9,
      delivery_time: 30,
      image_url: "https://dummyimage.com/300x200/339966/ffffff",
    },
    {
      id: 15,
      name: "BBQ Junction",
      cuisines: ["Barbecue", "American"],
      rating: 4.5,
      delivery_time: 40,
      image_url: "https://dummyimage.com/300x200/993300/ffffff",
    },
  ];

  export default resData;